import { PrismaClient } from '@prisma/client';
import { randomUUID } from 'crypto';

const db = new PrismaClient();

// Helper to create date in IST (UTC+5:30)
function istDate(daysAgo: number = 0, hoursAgo: number = 0): Date {
  const now = new Date();
  const istOffset = 5.5 * 60 * 60 * 1000;
  const utc = now.getTime() + now.getTimezoneOffset() * 60 * 1000 + istOffset;
  const d = new Date(utc - daysAgo * 86400000 - hoursAgo * 3600000);
  return d;
}

const operators = [
  'Tata Power EZ Charge', 'MG Motor Charge Station', 'Ather Grid',
  'ChargeZone', 'Zeon Charging', 'Statiq', 'EV Motors India',
  'Fortum India', 'Magenta Power', 'Azure Power',
  'BPCL Fuel Stations', 'Indian Oil EV', 'HPCL EV',
  'NTPC EV Charging', 'EESL Charging'
];

const amenitiesList = [
  'Restroom, Cafe, WiFi', 'Restroom, Food Court', 'Restroom, Parking',
  'Cafe, WiFi, Parking', 'Restroom, Cafe, Shopping', 'Restroom, Lounge',
  'Parking, Restroom', 'Food Court, Parking', 'WiFi, Cafe, Lounge',
  'Restroom, Cafe, Food Court, WiFi'
];

const paymentMethodsList = [
  'UPI, Card, Cash', 'UPI, Card, App', 'UPI, NFC, Card',
  'App Only, UPI', 'UPI, Card, Wallet', 'UPI, Cash, Card, App',
  'NFC, UPI, Card', 'RFID, UPI, Card'
];

interface StationInput {
  name: string;
  operator: string;
  state: string;
  district: string;
  city: string;
  address: string;
  pinCode: string;
  highway?: string;
  latitude: number;
  longitude: number;
  totalChargers: number;
  acChargers: number;
  dcFastChargers: number;
  ultraFastChargers: number;
  ccs2Chargers: number;
  chademoChargers: number;
  gbtChargers: number;
  type2Chargers: number;
  bharatAC001: number;
  bharatDC001: number;
  teslaCompatible: number;
  powerRatingsKW: string;
  is24x7: boolean;
  amenities: string;
  parkingAvailable: boolean;
  paymentMethods: string;
  status: string;
  dateDetected: Date;
  dateOperational: Date;
}

// Comprehensive station data across India
const stations: StationInput[] = [
  // DELHI NCR
  { name: 'Connaught Place EV Hub', operator: 'Tata Power EZ Charge', state: 'Delhi', district: 'New Delhi', city: 'New Delhi', address: 'A Block, Connaught Place', pinCode: '110001', latitude: 28.6315, longitude: 77.2167, totalChargers: 8, acChargers: 4, dcFastChargers: 3, ultraFastChargers: 1, ccs2Chargers: 3, chademoChargers: 1, gbtChargers: 0, type2Chargers: 4, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 1, powerRatingsKW: '7.4, 22, 50, 150', is24x7: true, amenities: 'Restroom, Cafe, WiFi, Shopping', parkingAvailable: true, paymentMethods: 'UPI, Card, Cash, App', status: 'operational', dateDetected: istDate(365, 0), dateOperational: istDate(360, 0) },
  { name: 'Saket City Walk Station', operator: 'ChargeZone', state: 'Delhi', district: 'South Delhi', city: 'New Delhi', address: 'Select Citywalk Mall, Saket', pinCode: '110017', latitude: 28.5265, longitude: 77.2062, totalChargers: 6, acChargers: 3, dcFastChargers: 2, ultraFastChargers: 1, ccs2Chargers: 2, chademoChargers: 0, gbtChargers: 0, type2Chargers: 3, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 1, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom, Food Court, WiFi, Parking', parkingAvailable: true, paymentMethods: 'UPI, Card, App', status: 'operational', dateDetected: istDate(300, 0), dateOperational: istDate(295, 0) },
  { name: 'Karol Bagh Charging Plaza', operator: 'Statiq', state: 'Delhi', district: 'Central Delhi', city: 'New Delhi', address: 'GH-12, Padam Singh Road, Karol Bagh', pinCode: '110005', latitude: 28.6512, longitude: 77.1909, totalChargers: 4, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 1, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 1, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: false, amenities: 'Restroom, Parking', parkingAvailable: true, paymentMethods: 'UPI, NFC, Card', status: 'operational', dateDetected: istDate(200, 0), dateOperational: istDate(195, 0) },
  { name: 'Dwarka Sector 21 Metro', operator: 'EV Motors India', state: 'Delhi', district: 'South West Delhi', city: 'Dwarka', address: 'Metro Station Parking, Sector 21', pinCode: '110075', latitude: 28.5733, longitude: 77.0423, totalChargers: 5, acChargers: 3, dcFastChargers: 2, ultraFastChargers: 0, ccs2Chargers: 2, chademoChargers: 0, gbtChargers: 0, type2Chargers: 3, bharatAC001: 1, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: true, amenities: 'Restroom, WiFi', parkingAvailable: true, paymentMethods: 'UPI, Card, Wallet', status: 'operational', dateDetected: istDate(180, 0), dateOperational: istDate(175, 0) },
  { name: 'Nehru Place EV Station', operator: 'Magenta Power', state: 'Delhi', district: 'South East Delhi', city: 'New Delhi', address: 'Hemkunt Tower, Nehru Place', pinCode: '110019', latitude: 28.5494, longitude: 77.2512, totalChargers: 3, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 0, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: false, amenities: 'Restroom', parkingAvailable: true, paymentMethods: 'UPI, Card', status: 'operational', dateDetected: istDate(150, 0), dateOperational: istDate(145, 0) },

  // GURGAON
  { name: 'Cyber Hub EV Plaza', operator: 'Tata Power EZ Charge', state: 'Haryana', district: 'Gurugram', city: 'Gurugram', address: 'DLF Cyber Hub, Golf Course Road', pinCode: '122002', latitude: 28.4947, longitude: 77.0887, totalChargers: 10, acChargers: 5, dcFastChargers: 3, ultraFastChargers: 2, ccs2Chargers: 4, chademoChargers: 1, gbtChargers: 0, type2Chargers: 5, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 2, powerRatingsKW: '7.4, 22, 50, 150', is24x7: true, amenities: 'Restroom, Cafe, WiFi, Shopping, Lounge', parkingAvailable: true, paymentMethods: 'UPI, Card, Cash, App', status: 'operational', dateDetected: istDate(400, 0), dateOperational: istDate(395, 0) },
  { name: 'MG Road Gurgaon Station', operator: 'Zeon Charging', state: 'Haryana', district: 'Gurugram', city: 'Gurugram', address: 'MG Road Metro Station', pinCode: '122002', latitude: 28.4784, longitude: 77.0928, totalChargers: 6, acChargers: 3, dcFastChargers: 2, ultraFastChargers: 1, ccs2Chargers: 2, chademoChargers: 0, gbtChargers: 0, type2Chargers: 3, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 1, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom, WiFi', parkingAvailable: true, paymentMethods: 'UPI, NFC, Card', status: 'operational', dateDetected: istDate(250, 0), dateOperational: istDate(245, 0) },
  { name: 'Sector 29 Market Hub', operator: 'Statiq', state: 'Haryana', district: 'Gurugram', city: 'Gurugram', address: 'Sector 29 Market Complex', pinCode: '122001', latitude: 28.4594, longitude: 77.0266, totalChargers: 4, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 1, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: false, amenities: 'Restroom, Food Court', parkingAvailable: true, paymentMethods: 'UPI, Card, App', status: 'operational', dateDetected: istDate(120, 0), dateOperational: istDate(115, 0) },

  // NOIDA
  { name: 'Sector 18 Atta Market EV', operator: 'ChargeZone', state: 'Uttar Pradesh', district: 'Gautam Buddh Nagar', city: 'Noida', address: 'Atta Market, Sector 18', pinCode: '201301', latitude: 28.5700, longitude: 77.3221, totalChargers: 6, acChargers: 3, dcFastChargers: 2, ultraFastChargers: 1, ccs2Chargers: 2, chademoChargers: 0, gbtChargers: 0, type2Chargers: 3, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 1, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom, Cafe, WiFi', parkingAvailable: true, paymentMethods: 'UPI, Card, Cash', status: 'operational', dateDetected: istDate(280, 0), dateOperational: istDate(275, 0) },
  { name: 'Botanical Garden Metro Station', operator: 'Ather Grid', state: 'Uttar Pradesh', district: 'Gautam Buddh Nagar', city: 'Noida', address: 'Botanical Garden Metro Parking', pinCode: '201303', latitude: 28.5427, longitude: 77.3312, totalChargers: 4, acChargers: 3, dcFastChargers: 1, ultraFastChargers: 0, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 3, bharatAC001: 1, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: true, amenities: 'Restroom, Parking', parkingAvailable: true, paymentMethods: 'UPI, App', status: 'operational', dateDetected: istDate(220, 0), dateOperational: istDate(215, 0) },

  // MUMBAI
  { name: 'BKC Charging Hub', operator: 'Tata Power EZ Charge', state: 'Maharashtra', district: 'Mumbai', city: 'Mumbai', address: 'Bandra Kurla Complex, J Block', pinCode: '400051', latitude: 19.0728, longitude: 72.8681, totalChargers: 12, acChargers: 6, dcFastChargers: 4, ultraFastChargers: 2, ccs2Chargers: 5, chademoChargers: 1, gbtChargers: 0, type2Chargers: 6, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 2, powerRatingsKW: '7.4, 22, 50, 150', is24x7: true, amenities: 'Restroom, Cafe, WiFi, Shopping, Lounge, Parking', parkingAvailable: true, paymentMethods: 'UPI, Card, Cash, App, NFC', status: 'operational', dateDetected: istDate(450, 0), dateOperational: istDate(445, 0) },
  { name: 'Andheri West EV Station', operator: 'Statiq', state: 'Maharashtra', district: 'Mumbai', city: 'Mumbai', address: 'Lokhandwala Complex, Andheri West', pinCode: '400053', latitude: 19.1364, longitude: 72.8296, totalChargers: 5, acChargers: 3, dcFastChargers: 1, ultraFastChargers: 1, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 3, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 1, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom, Cafe', parkingAvailable: true, paymentMethods: 'UPI, Card, App', status: 'operational', dateDetected: istDate(320, 0), dateOperational: istDate(315, 0) },
  { name: 'Powai Hiranandani EV', operator: 'ChargeZone', state: 'Maharashtra', district: 'Mumbai', city: 'Mumbai', address: 'Hiranandani Gardens, Powai', pinCode: '400076', latitude: 19.1197, longitude: 72.9056, totalChargers: 4, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 1, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: false, amenities: 'Restroom, WiFi', parkingAvailable: true, paymentMethods: 'UPI, Card', status: 'operational', dateDetected: istDate(190, 0), dateOperational: istDate(185, 0) },
  { name: 'Worli Sea Link EV', operator: 'Magenta Power', state: 'Maharashtra', district: 'Mumbai', city: 'Mumbai', address: 'Worli Naka, Near Sea Link', pinCode: '400030', latitude: 19.0175, longitude: 72.8172, totalChargers: 3, acChargers: 1, dcFastChargers: 1, ultraFastChargers: 1, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 1, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 1, powerRatingsKW: '7.4, 50, 120', is24x7: true, amenities: 'Restroom', parkingAvailable: true, paymentMethods: 'UPI, Card', status: 'operational', dateDetected: istDate(90, 0), dateOperational: istDate(85, 0) },

  // BANGALORE
  { name: 'MG Road Bangalore EV Hub', operator: 'Ather Grid', state: 'Karnataka', district: 'Bangalore Urban', city: 'Bangalore', address: 'MG Road Metro Station', pinCode: '560001', latitude: 12.9716, longitude: 77.6070, totalChargers: 8, acChargers: 4, dcFastChargers: 3, ultraFastChargers: 1, ccs2Chargers: 3, chademoChargers: 0, gbtChargers: 0, type2Chargers: 4, bharatAC001: 1, bharatDC001: 0, teslaCompatible: 1, powerRatingsKW: '7.4, 22, 50, 150', is24x7: true, amenities: 'Restroom, Cafe, WiFi, Shopping', parkingAvailable: true, paymentMethods: 'UPI, Card, App, NFC', status: 'operational', dateDetected: istDate(500, 0), dateOperational: istDate(495, 0) },
  { name: 'Whitefield EV Station', operator: 'Tata Power EZ Charge', state: 'Karnataka', district: 'Bangalore Urban', city: 'Bangalore', address: 'ITPL Road, Whitefield', pinCode: '560066', latitude: 12.9698, longitude: 77.7500, totalChargers: 7, acChargers: 3, dcFastChargers: 3, ultraFastChargers: 1, ccs2Chargers: 3, chademoChargers: 0, gbtChargers: 0, type2Chargers: 3, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 1, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom, Cafe, WiFi', parkingAvailable: true, paymentMethods: 'UPI, Card, App', status: 'operational', dateDetected: istDate(380, 0), dateOperational: istDate(375, 0) },
  { name: 'Electronic City Charge Point', operator: 'Zeon Charging', state: 'Karnataka', district: 'Bangalore Urban', city: 'Bangalore', address: 'Phase 1, Electronic City', pinCode: '560100', latitude: 12.8441, longitude: 77.6593, totalChargers: 6, acChargers: 3, dcFastChargers: 2, ultraFastChargers: 1, ccs2Chargers: 2, chademoChargers: 0, gbtChargers: 0, type2Chargers: 3, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: true, amenities: 'Restroom, Food Court', parkingAvailable: true, paymentMethods: 'UPI, Card', status: 'operational', dateDetected: istDate(310, 0), dateOperational: istDate(305, 0) },
  { name: 'HSR Layout EV Hub', operator: 'Statiq', state: 'Karnataka', district: 'Bangalore Urban', city: 'Bangalore', address: '27th Main, HSR Layout', pinCode: '560102', latitude: 12.9116, longitude: 77.6474, totalChargers: 4, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 1, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: false, amenities: 'Restroom, Cafe', parkingAvailable: true, paymentMethods: 'UPI, Card, App', status: 'operational', dateDetected: istDate(160, 0), dateOperational: istDate(155, 0) },

  // HYDERABAD
  { name: 'HITEC City EV Station', operator: 'Tata Power EZ Charge', state: 'Telangana', district: 'Hyderabad', city: 'Hyderabad', address: 'Cyber Towers, HITEC City', pinCode: '500081', latitude: 17.4435, longitude: 78.3772, totalChargers: 8, acChargers: 4, dcFastChargers: 3, ultraFastChargers: 1, ccs2Chargers: 3, chademoChargers: 0, gbtChargers: 0, type2Chargers: 4, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 1, powerRatingsKW: '7.4, 22, 50, 150', is24x7: true, amenities: 'Restroom, Cafe, WiFi, Lounge', parkingAvailable: true, paymentMethods: 'UPI, Card, App, NFC', status: 'operational', dateDetected: istDate(420, 0), dateOperational: istDate(415, 0) },
  { name: 'Gachibowli Charging Plaza', operator: 'ChargeZone', state: 'Telangana', district: 'Hyderabad', city: 'Hyderabad', address: 'Financial District, Gachibowli', pinCode: '500032', latitude: 17.4401, longitude: 78.3489, totalChargers: 6, acChargers: 3, dcFastChargers: 2, ultraFastChargers: 1, ccs2Chargers: 2, chademoChargers: 0, gbtChargers: 0, type2Chargers: 3, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom, WiFi, Parking', parkingAvailable: true, paymentMethods: 'UPI, Card, App', status: 'operational', dateDetected: istDate(280, 0), dateOperational: istDate(275, 0) },
  { name: 'Jubilee Hills EV Point', operator: 'EV Motors India', state: 'Telangana', district: 'Hyderabad', city: 'Hyderabad', address: 'Road No. 36, Jubilee Hills', pinCode: '500033', latitude: 17.4156, longitude: 78.4063, totalChargers: 4, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 1, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: false, amenities: 'Restroom, Cafe', parkingAvailable: true, paymentMethods: 'UPI, Card', status: 'operational', dateDetected: istDate(140, 0), dateOperational: istDate(135, 0) },

  // CHENNAI
  { name: 'OMR Thoraipakkam EV', operator: 'Tata Power EZ Charge', state: 'Tamil Nadu', district: 'Chennai', city: 'Chennai', address: 'Old Mahabalipuram Road, Thoraipakkam', pinCode: '600097', latitude: 12.9320, longitude: 80.2420, totalChargers: 6, acChargers: 3, dcFastChargers: 2, ultraFastChargers: 1, ccs2Chargers: 2, chademoChargers: 0, gbtChargers: 0, type2Chargers: 3, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 1, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom, Cafe, WiFi', parkingAvailable: true, paymentMethods: 'UPI, Card, App', status: 'operational', dateDetected: istDate(350, 0), dateOperational: istDate(345, 0) },
  { name: 'Anna Nagar EV Station', operator: 'Statiq', state: 'Tamil Nadu', district: 'Chennai', city: 'Chennai', address: 'W-128, 3rd Avenue, Anna Nagar', pinCode: '600040', latitude: 13.0873, longitude: 80.2086, totalChargers: 4, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 1, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: true, amenities: 'Restroom, Parking', parkingAvailable: true, paymentMethods: 'UPI, Card', status: 'operational', dateDetected: istDate(200, 0), dateOperational: istDate(195, 0) },
  { name: 'Guindy Industrial EV', operator: 'Zeon Charging', state: 'Tamil Nadu', district: 'Chennai', city: 'Chennai', address: 'Guindy Industrial Estate', pinCode: '600032', latitude: 13.0067, longitude: 80.2206, totalChargers: 5, acChargers: 2, dcFastChargers: 2, ultraFastChargers: 1, ccs2Chargers: 2, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom', parkingAvailable: true, paymentMethods: 'UPI, Card, App', status: 'operational', dateDetected: istDate(170, 0), dateOperational: istDate(165, 0) },

  // PUNE
  { name: 'Hinjewadi IT Park EV', operator: 'Tata Power EZ Charge', state: 'Maharashtra', district: 'Pune', city: 'Pune', address: 'Phase 1, Hinjewadi IT Park', pinCode: '411057', latitude: 18.5921, longitude: 73.7362, totalChargers: 8, acChargers: 4, dcFastChargers: 3, ultraFastChargers: 1, ccs2Chargers: 3, chademoChargers: 0, gbtChargers: 0, type2Chargers: 4, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 1, powerRatingsKW: '7.4, 22, 50, 150', is24x7: true, amenities: 'Restroom, Cafe, WiFi, Parking', parkingAvailable: true, paymentMethods: 'UPI, Card, App, NFC', status: 'operational', dateDetected: istDate(380, 0), dateOperational: istDate(375, 0) },
  { name: 'Viman Nagar EV Hub', operator: 'ChargeZone', state: 'Maharashtra', district: 'Pune', city: 'Pune', address: 'Dutta Mandir Chowk, Viman Nagar', pinCode: '411014', latitude: 18.5652, longitude: 73.9093, totalChargers: 5, acChargers: 2, dcFastChargers: 2, ultraFastChargers: 1, ccs2Chargers: 2, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom, Cafe, WiFi', parkingAvailable: true, paymentMethods: 'UPI, Card, App', status: 'operational', dateDetected: istDate(240, 0), dateOperational: istDate(235, 0) },

  // KOLKATA
  { name: 'Salt Lake Sector V EV', operator: 'Tata Power EZ Charge', state: 'West Bengal', district: 'Kolkata', city: 'Kolkata', address: 'Sector V, Salt Lake', pinCode: '700091', latitude: 22.5726, longitude: 88.3639, totalChargers: 6, acChargers: 3, dcFastChargers: 2, ultraFastChargers: 1, ccs2Chargers: 2, chademoChargers: 0, gbtChargers: 0, type2Chargers: 3, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 1, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom, Cafe, WiFi', parkingAvailable: true, paymentMethods: 'UPI, Card, App', status: 'operational', dateDetected: istDate(330, 0), dateOperational: istDate(325, 0) },
  { name: 'Park Street EV Station', operator: 'EV Motors India', state: 'West Bengal', district: 'Kolkata', city: 'Kolkata', address: 'Park Street, Chowringhee', pinCode: '700016', latitude: 22.5480, longitude: 88.3495, totalChargers: 4, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 1, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: true, amenities: 'Restroom, Cafe', parkingAvailable: true, paymentMethods: 'UPI, Card', status: 'operational', dateDetected: istDate(210, 0), dateOperational: istDate(205, 0) },

  // AHMEDABAD
  { name: 'SG Highway EV Hub', operator: 'Tata Power EZ Charge', state: 'Gujarat', district: 'Ahmedabad', city: 'Ahmedabad', address: 'Satellite, SG Highway', pinCode: '380015', latitude: 23.0326, longitude: 72.5262, totalChargers: 7, acChargers: 3, dcFastChargers: 3, ultraFastChargers: 1, ccs2Chargers: 3, chademoChargers: 0, gbtChargers: 0, type2Chargers: 3, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 1, powerRatingsKW: '7.4, 22, 50, 150', is24x7: true, amenities: 'Restroom, Cafe, WiFi, Parking', parkingAvailable: true, paymentMethods: 'UPI, Card, Cash, App', status: 'operational', dateDetected: istDate(400, 0), dateOperational: istDate(395, 0) },
  { name: 'Bopal EV Station', operator: 'Zeon Charging', state: 'Gujarat', district: 'Ahmedabad', city: 'Ahmedabad', address: 'Bopal Road, South Bopal', pinCode: '380058', latitude: 23.0090, longitude: 72.4862, totalChargers: 4, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 1, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: false, amenities: 'Restroom', parkingAvailable: true, paymentMethods: 'UPI, Card', status: 'operational', dateDetected: istDate(130, 0), dateOperational: istDate(125, 0) },

  // JAIPUR
  { name: 'Tonk Road EV Plaza', operator: 'ChargeZone', state: 'Rajasthan', district: 'Jaipur', city: 'Jaipur', address: 'Tonk Road, Near DCM', pinCode: '302015', latitude: 26.8962, longitude: 75.7918, totalChargers: 5, acChargers: 2, dcFastChargers: 2, ultraFastChargers: 1, ccs2Chargers: 2, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom, Cafe', parkingAvailable: true, paymentMethods: 'UPI, Card, App', status: 'operational', dateDetected: istDate(260, 0), dateOperational: istDate(255, 0) },
  { name: 'Vaishali Nagar EV', operator: 'Statiq', state: 'Rajasthan', district: 'Jaipur', city: 'Jaipur', address: 'Main Market, Vaishali Nagar', pinCode: '302021', latitude: 26.9037, longitude: 75.7871, totalChargers: 3, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 0, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: false, amenities: 'Restroom', parkingAvailable: true, paymentMethods: 'UPI, Card', status: 'operational', dateDetected: istDate(100, 0), dateOperational: istDate(95, 0) },

  // HIGHWAY STATIONS
  { name: 'NH48 Manesar Expressway', operator: 'Tata Power EZ Charge', state: 'Haryana', district: 'Gurugram', city: 'Manesar', address: 'KMP Expressway, Manesar', pinCode: '122050', highway: 'NH48', latitude: 28.3588, longitude: 76.9397, totalChargers: 6, acChargers: 2, dcFastChargers: 3, ultraFastChargers: 1, ccs2Chargers: 3, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 1, powerRatingsKW: '7.4, 50, 150', is24x7: true, amenities: 'Restroom, Cafe, Parking', parkingAvailable: true, paymentMethods: 'UPI, Card, Cash', status: 'operational', dateDetected: istDate(340, 0), dateOperational: istDate(335, 0) },
  { name: 'NH8 Jaipur Highway EV', operator: 'Indian Oil EV', state: 'Rajasthan', district: 'Alwar', city: 'Alwar', address: 'NH8, Near Shahpura', pinCode: '301014', highway: 'NH8', latitude: 27.2279, longitude: 76.1888, totalChargers: 4, acChargers: 1, dcFastChargers: 2, ultraFastChargers: 1, ccs2Chargers: 2, chademoChargers: 0, gbtChargers: 0, type2Chargers: 1, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '22, 50, 120', is24x7: true, amenities: 'Restroom, Fuel Station', parkingAvailable: true, paymentMethods: 'UPI, Card, Cash', status: 'operational', dateDetected: istDate(200, 0), dateOperational: istDate(195, 0) },
  { name: 'Mumbai-Pune Expressway Lonavala', operator: 'Tata Power EZ Charge', state: 'Maharashtra', district: 'Pune', city: 'Lonavala', address: 'Mumbai-Pune Expressway, Lonavala', pinCode: '410401', highway: 'Mumbai-Pune Expressway', latitude: 18.7546, longitude: 73.4062, totalChargers: 8, acChargers: 3, dcFastChargers: 3, ultraFastChargers: 2, ccs2Chargers: 4, chademoChargers: 0, gbtChargers: 0, type2Chargers: 3, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 1, powerRatingsKW: '7.4, 22, 50, 150', is24x7: true, amenities: 'Restroom, Cafe, WiFi, Parking, Food Court', parkingAvailable: true, paymentMethods: 'UPI, Card, Cash, App', status: 'operational', dateDetected: istDate(450, 0), dateOperational: istDate(445, 0) },
  { name: 'Bangalore-Hyderabad Hwy Kurnool', operator: 'ChargeZone', state: 'Andhra Pradesh', district: 'Kurnool', city: 'Kurnool', address: 'NH44, Kurnool Bypass', pinCode: '518001', highway: 'NH44', latitude: 15.8281, longitude: 78.0373, totalChargers: 4, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 1, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: true, amenities: 'Restroom, Cafe', parkingAvailable: true, paymentMethods: 'UPI, Card', status: 'operational', dateDetected: istDate(150, 0), dateOperational: istDate(145, 0) },
  { name: 'Delhi-Agra Hwy Mathura', operator: 'BPCL Fuel Stations', state: 'Uttar Pradesh', district: 'Mathura', city: 'Mathura', address: 'NH19, Mathura Bypass', pinCode: '281001', highway: 'NH19', latitude: 27.4924, longitude: 77.6737, totalChargers: 4, acChargers: 1, dcFastChargers: 2, ultraFastChargers: 1, ccs2Chargers: 2, chademoChargers: 0, gbtChargers: 0, type2Chargers: 1, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '22, 50, 120', is24x7: true, amenities: 'Restroom, Fuel Station, Cafe', parkingAvailable: true, paymentMethods: 'UPI, Card, Cash', status: 'operational', dateDetected: istDate(300, 0), dateOperational: istDate(295, 0) },
  { name: 'Chennai-Bangalore Hwy Vellore', operator: 'HPCL EV', state: 'Tamil Nadu', district: 'Vellore', city: 'Vellore', address: 'NH48, Vellore Bypass', pinCode: '632001', highway: 'NH48', latitude: 12.9165, longitude: 79.1325, totalChargers: 4, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 1, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: true, amenities: 'Restroom, Fuel Station', parkingAvailable: true, paymentMethods: 'UPI, Card, Cash', status: 'operational', dateDetected: istDate(180, 0), dateOperational: istDate(175, 0) },

  // MORE CITIES
  { name: 'Lal Darwaja EV Station', operator: 'EV Motors India', state: 'Gujarat', district: 'Ahmedabad', city: 'Ahmedabad', address: 'Lal Darwaja, Old City', pinCode: '380001', latitude: 23.0258, longitude: 72.5714, totalChargers: 3, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 0, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 1, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: false, amenities: 'Restroom', parkingAvailable: false, paymentMethods: 'UPI, Cash', status: 'operational', dateDetected: istDate(160, 0), dateOperational: istDate(155, 0) },
  { name: 'Kochi MG Road EV', operator: 'Tata Power EZ Charge', state: 'Kerala', district: 'Ernakulam', city: 'Kochi', address: 'MG Road, Ernakulam', pinCode: '682011', latitude: 9.9816, longitude: 76.2999, totalChargers: 4, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 1, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom, Cafe', parkingAvailable: true, paymentMethods: 'UPI, Card', status: 'operational', dateDetected: istDate(230, 0), dateOperational: istDate(225, 0) },
  { name: 'Lucknow Hazratganj EV', operator: 'Statiq', state: 'Uttar Pradesh', district: 'Lucknow', city: 'Lucknow', address: 'Hazratganj Market', pinCode: '226001', latitude: 26.8467, longitude: 80.9462, totalChargers: 4, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 1, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: false, amenities: 'Restroom', parkingAvailable: true, paymentMethods: 'UPI, Card, Cash', status: 'operational', dateDetected: istDate(110, 0), dateOperational: istDate(105, 0) },
  { name: 'Bhubaneswar Saheed Nagar EV', operator: 'ChargeZone', state: 'Odisha', district: 'Khordha', city: 'Bhubaneswar', address: 'Saheed Nagar, Near CRP Square', pinCode: '751007', latitude: 20.2926, longitude: 85.8406, totalChargers: 3, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 0, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: false, amenities: 'Restroom', parkingAvailable: true, paymentMethods: 'UPI, Card', status: 'operational', dateDetected: istDate(80, 0), dateOperational: istDate(75, 0) },
  { name: 'Indore Vijay Nagar EV', operator: 'Zeon Charging', state: 'Madhya Pradesh', district: 'Indore', city: 'Indore', address: 'Vijay Nagar Square', pinCode: '452010', latitude: 22.7196, longitude: 75.8577, totalChargers: 4, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 1, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: true, amenities: 'Restroom, Cafe', parkingAvailable: true, paymentMethods: 'UPI, Card', status: 'operational', dateDetected: istDate(95, 0), dateOperational: istDate(90, 0) },
  { name: 'Chandigarh Sector 17 EV', operator: 'Tata Power EZ Charge', state: 'Chandigarh', district: 'Chandigarh', city: 'Chandigarh', address: 'Sector 17 Plaza', pinCode: '160017', latitude: 30.7333, longitude: 76.7794, totalChargers: 5, acChargers: 2, dcFastChargers: 2, ultraFastChargers: 1, ccs2Chargers: 2, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 1, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom, Cafe, WiFi', parkingAvailable: true, paymentMethods: 'UPI, Card, Cash', status: 'operational', dateDetected: istDate(270, 0), dateOperational: istDate(265, 0) },
  { name: 'Guwahati GS Road EV', operator: 'EV Motors India', state: 'Assam', district: 'Kamrup', city: 'Guwahati', address: 'GS Road, Bhangagarh', pinCode: '781005', latitude: 26.1458, longitude: 91.7903, totalChargers: 3, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 0, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: false, amenities: 'Restroom', parkingAvailable: true, paymentMethods: 'UPI, Card', status: 'operational', dateDetected: istDate(60, 0), dateOperational: istDate(55, 0) },
  { name: 'Thiruvananthapuram MG Road', operator: 'Statiq', state: 'Kerala', district: 'Thiruvananthapuram', city: 'Thiruvananthapuram', address: 'MG Road, Statue Junction', pinCode: '695001', latitude: 8.4946, longitude: 76.9523, totalChargers: 3, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 0, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: false, amenities: 'Restroom', parkingAvailable: true, paymentMethods: 'UPI, Card', status: 'operational', dateDetected: istDate(70, 0), dateOperational: istDate(65, 0) },

  // NEWLY ADDED STATIONS (this week)
  { name: 'Noida Expressway Mahamaya Flyover', operator: 'Tata Power EZ Charge', state: 'Uttar Pradesh', district: 'Gautam Buddh Nagar', city: 'Noida', address: 'Noida-Greater Noida Expressway', pinCode: '201310', highway: 'Noida Expressway', latitude: 28.5355, longitude: 77.3910, totalChargers: 6, acChargers: 3, dcFastChargers: 2, ultraFastChargers: 1, ccs2Chargers: 2, chademoChargers: 0, gbtChargers: 0, type2Chargers: 3, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 1, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom, Cafe, WiFi, Parking', parkingAvailable: true, paymentMethods: 'UPI, Card, App, NFC', status: 'operational', dateDetected: istDate(2, 0), dateOperational: istDate(1, 0) },
  { name: 'Gurgaon Golf Course Ext Road', operator: 'ChargeZone', state: 'Haryana', district: 'Gurugram', city: 'Gurugram', address: 'Golf Course Extension Road, Sector 57', pinCode: '122011', latitude: 28.4262, longitude: 77.1051, totalChargers: 4, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 1, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom, Cafe', parkingAvailable: true, paymentMethods: 'UPI, Card, App', status: 'operational', dateDetected: istDate(3, 0), dateOperational: istDate(2, 0) },
  { name: 'Delhi IGI Airport T3 EV', operator: 'Tata Power EZ Charge', state: 'Delhi', district: 'South West Delhi', city: 'New Delhi', address: 'IGI Airport Terminal 3 Parking', pinCode: '110037', latitude: 28.5562, longitude: 77.1000, totalChargers: 10, acChargers: 4, dcFastChargers: 4, ultraFastChargers: 2, ccs2Chargers: 5, chademoChargers: 1, gbtChargers: 0, type2Chargers: 4, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 2, powerRatingsKW: '7.4, 22, 50, 150', is24x7: true, amenities: 'Restroom, Cafe, WiFi, Lounge, Shopping, Parking', parkingAvailable: true, paymentMethods: 'UPI, Card, Cash, App, NFC', status: 'operational', dateDetected: istDate(1, 0), dateOperational: istDate(0, 0) },
  { name: 'Mumbai Juhu Beach EV', operator: 'Magenta Power', state: 'Maharashtra', district: 'Mumbai', city: 'Mumbai', address: 'Juhu Tara Road, Juhu', pinCode: '400049', latitude: 19.0986, longitude: 72.8265, totalChargers: 4, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 1, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom, Cafe, WiFi', parkingAvailable: true, paymentMethods: 'UPI, Card', status: 'operational', dateDetected: istDate(4, 0), dateOperational: istDate(3, 0) },

  // CLOSED / TEMPORARILY UNAVAILABLE
  { name: 'Nehru Place EV Station', operator: 'Magenta Power', state: 'Delhi', district: 'South East Delhi', city: 'New Delhi', address: 'Hemkunt Tower, Nehru Place', pinCode: '110019', latitude: 28.5494, longitude: 77.2512, totalChargers: 3, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 0, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: false, amenities: 'Restroom', parkingAvailable: true, paymentMethods: 'UPI, Card', status: 'under_maintenance', dateDetected: istDate(150, 0), dateOperational: istDate(145, 0) },

  // ADDITIONAL stations for data richness
  { name: 'Faridabad Sector 15 EV', operator: 'Statiq', state: 'Haryana', district: 'Faridabad', city: 'Faridabad', address: 'Sector 15 Market', pinCode: '121007', latitude: 28.4089, longitude: 77.3178, totalChargers: 3, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 0, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: false, amenities: 'Restroom', parkingAvailable: true, paymentMethods: 'UPI, Card', status: 'operational', dateDetected: istDate(45, 0), dateOperational: istDate(40, 0) },
  { name: 'Ghaziabad Vaishali EV', operator: 'ChargeZone', state: 'Uttar Pradesh', district: 'Ghaziabad', city: 'Ghaziabad', address: 'Vaishali Metro Station', pinCode: '201010', latitude: 28.6562, longitude: 77.3311, totalChargers: 4, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 1, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom, Parking', parkingAvailable: true, paymentMethods: 'UPI, Card, App', status: 'operational', dateDetected: istDate(35, 0), dateOperational: istDate(30, 0) },
  { name: 'Thane Viviana Mall EV', operator: 'Tata Power EZ Charge', state: 'Maharashtra', district: 'Thane', city: 'Thane', address: 'Viviana Mall, Eastern Express Highway', pinCode: '400601', latitude: 19.2183, longitude: 72.9781, totalChargers: 6, acChargers: 3, dcFastChargers: 2, ultraFastChargers: 1, ccs2Chargers: 2, chademoChargers: 0, gbtChargers: 0, type2Chargers: 3, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 1, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom, Cafe, WiFi, Shopping, Parking', parkingAvailable: true, paymentMethods: 'UPI, Card, Cash, App', status: 'operational', dateDetected: istDate(20, 0), dateOperational: istDate(15, 0) },
  { name: 'Navi Mumbai Seawoods EV', operator: 'Zeon Charging', state: 'Maharashtra', district: 'Thane', city: 'Navi Mumbai', address: 'Seawoods Grand Central Mall', pinCode: '400706', latitude: 19.0216, longitude: 73.0216, totalChargers: 5, acChargers: 2, dcFastChargers: 2, ultraFastChargers: 1, ccs2Chargers: 2, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom, Cafe, WiFi, Shopping', parkingAvailable: true, paymentMethods: 'UPI, Card, App', status: 'operational', dateDetected: istDate(10, 0), dateOperational: istDate(5, 0) },
  { name: 'Coimbatore Avinashi Road EV', operator: 'Tata Power EZ Charge', state: 'Tamil Nadu', district: 'Coimbatore', city: 'Coimbatore', address: 'Avinashi Road, Near Fun Republic', pinCode: '641018', latitude: 11.0168, longitude: 77.0155, totalChargers: 4, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 1, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom, Cafe', parkingAvailable: true, paymentMethods: 'UPI, Card', status: 'operational', dateDetected: istDate(8, 0), dateOperational: istDate(5, 0) },
  { name: 'Visakhapatnam Beach Road EV', operator: 'EV Motors India', state: 'Andhra Pradesh', district: 'Visakhapatnam', city: 'Visakhapatnam', address: 'Beach Road, RK Beach', pinCode: '530001', latitude: 17.7236, longitude: 83.2893, totalChargers: 3, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 0, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: false, amenities: 'Restroom', parkingAvailable: true, paymentMethods: 'UPI, Card', status: 'operational', dateDetected: istDate(14, 0), dateOperational: istDate(10, 0) },
  { name: 'Nagpur Dharampeth EV', operator: 'Statiq', state: 'Maharashtra', district: 'Nagpur', city: 'Nagpur', address: 'Dharampeth, Wardha Road', pinCode: '440012', latitude: 21.1458, longitude: 79.0882, totalChargers: 3, acChargers: 2, dcFastChargers: 1, ultraFastChargers: 0, ccs2Chargers: 1, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50', is24x7: false, amenities: 'Restroom', parkingAvailable: true, paymentMethods: 'UPI, Card', status: 'operational', dateDetected: istDate(12, 0), dateOperational: istDate(8, 0) },
  { name: 'Jaipur Ajmer Highway EV', operator: 'Indian Oil EV', state: 'Rajasthan', district: 'Jaipur', city: 'Jaipur', address: 'NH8, Ajmer Highway', pinCode: '302019', highway: 'NH8', latitude: 26.8614, longitude: 75.7437, totalChargers: 4, acChargers: 1, dcFastChargers: 2, ultraFastChargers: 1, ccs2Chargers: 2, chademoChargers: 0, gbtChargers: 0, type2Chargers: 1, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '22, 50, 120', is24x7: true, amenities: 'Restroom, Fuel Station, Cafe', parkingAvailable: true, paymentMethods: 'UPI, Card, Cash', status: 'operational', dateDetected: istDate(7, 0), dateOperational: istDate(4, 0) },
  { name: 'Surat Dumas Road EV', operator: 'ChargeZone', state: 'Gujarat', district: 'Surat', city: 'Surat', address: 'Dumas Road, Vesu', pinCode: '395007', latitude: 21.1635, longitude: 72.7954, totalChargers: 5, acChargers: 2, dcFastChargers: 2, ultraFastChargers: 1, ccs2Chargers: 2, chademoChargers: 0, gbtChargers: 0, type2Chargers: 2, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom, Cafe, WiFi', parkingAvailable: true, paymentMethods: 'UPI, Card, App', status: 'operational', dateDetected: istDate(6, 0), dateOperational: istDate(3, 0) },
  { name: 'Trivandrum Technopark EV', operator: 'Tata Power EZ Charge', state: 'Kerala', district: 'Thiruvananthapuram', city: 'Thiruvananthapuram', address: 'Technopark Campus', pinCode: '695581', latitude: 8.5573, longitude: 76.8855, totalChargers: 6, acChargers: 3, dcFastChargers: 2, ultraFastChargers: 1, ccs2Chargers: 2, chademoChargers: 0, gbtChargers: 0, type2Chargers: 3, bharatAC001: 0, bharatDC001: 0, teslaCompatible: 0, powerRatingsKW: '7.4, 22, 50, 120', is24x7: true, amenities: 'Restroom, Cafe, WiFi, Parking', parkingAvailable: true, paymentMethods: 'UPI, Card, App', status: 'operational', dateDetected: istDate(5, 0), dateOperational: istDate(2, 0) },
];

async function seedStations() {
  console.log('Seeding charging stations...');
  
  // Delete existing data
  await db.chargingStation.deleteMany();
  await db.chargingAlert.deleteMany();
  await db.routeAnalysis.deleteMany();
  await db.investmentOpportunity.deleteMany();
  await db.chargingDesert.deleteMany();

  // Insert stations
  for (const s of stations) {
    await db.chargingStation.create({ data: s });
  }
  console.log(`Seeded ${stations.length} charging stations`);
}

async function seedAlerts() {
  console.log('Seeding alerts...');
  const alerts = [
    { type: 'new_charger', severity: 'info', title: 'New Station: Delhi IGI Airport T3 EV', description: 'Tata Power EZ Charge commissioned 10 chargers at IGI Airport T3 Parking with CCS2, Type-2 and Tesla-compatible connectors.', location: 'New Delhi', timestamp: istDate(0, 2) },
    { type: 'new_charger', severity: 'info', title: 'New Station: Noida Expressway Mahamaya Flyover', description: '6 chargers operational with 120kW ultra-fast and DC fast charging.', location: 'Noida, UP', timestamp: istDate(1, 5) },
    { type: 'new_charger', severity: 'info', title: 'New Station: Gurgaon Golf Course Ext Road', description: 'ChargeZone launches 4 chargers including 120kW ultra-fast.', location: 'Gurugram, Haryana', timestamp: istDate(2, 3) },
    { type: 'new_charger', severity: 'info', title: 'New Station: Mumbai Juhu Beach EV', description: 'Magenta Power adds 4 chargers at Juhu Beach area.', location: 'Mumbai, Maharashtra', timestamp: istDate(3, 4) },
    { type: 'new_charger', severity: 'info', title: 'New Station: Surat Dumas Road EV', description: 'ChargeZone expands to Surat with 5 chargers.', location: 'Surat, Gujarat', timestamp: istDate(5, 1) },
    { type: 'new_charger', severity: 'info', title: 'New Station: Trivandrum Technopark EV', description: 'Tata Power EZ Charge adds 6 chargers at Technopark.', location: 'Thiruvananthapuram, Kerala', timestamp: istDate(4, 2) },
    { type: 'new_charger', severity: 'info', title: 'New Station: Thane Viviana Mall EV', description: '6 chargers now operational at Viviana Mall including Tesla-compatible.', location: 'Thane, Maharashtra', timestamp: istDate(18, 6) },
    { type: 'new_charger', severity: 'info', title: 'New Station: Navi Mumbai Seawoods EV', description: 'Zeon Charging opens 5-charger hub at Seawoods Grand Central.', location: 'Navi Mumbai, Maharashtra', timestamp: istDate(8, 3) },
    { type: 'new_charger', severity: 'info', title: 'New Station: Coimbatore Avinashi Road EV', description: 'Tata Power EZ Charge expands Tamil Nadu footprint.', location: 'Coimbatore, Tamil Nadu', timestamp: istDate(6, 5) },
    { type: 'new_charger', severity: 'info', title: 'New Station: Jaipur Ajmer Highway EV', description: 'Indian Oil EV installs 4 chargers on NH8 highway corridor.', location: 'Jaipur, Rajasthan', timestamp: istDate(5, 4) },
    { type: 'offline', severity: 'warning', title: 'Nehru Place EV Station Under Maintenance', description: 'Magenta Power station at Nehru Place is temporarily under maintenance. Expected to resume in 3 days.', location: 'New Delhi', timestamp: istDate(1, 8) },
    { type: 'highway_gap', severity: 'warning', title: 'NH44 Kurnool-Hyderabad Gap Alert', description: '200km stretch between Kurnool and Hyderabad has limited 24x7 fast charging. Only 2 stations found.', location: 'Kurnool - Hyderabad', timestamp: istDate(2, 10) },
    { type: 'route_unsafe', severity: 'critical', title: 'Leh-Manali Highway: No Charging Infrastructure', description: 'The 474km Leh-Manali Highway has zero EV charging stations. Not recommended for EV travel.', location: 'Leh-Manali Highway', timestamp: istDate(5, 6) },
    { type: 'operator_expansion', severity: 'info', title: 'Tata Power EZ Charge Expands to Surat', description: 'Tata Power commissioned 5 new chargers in Surat, marking entry into Gujarat tier-2 market.', location: 'Surat, Gujarat', timestamp: istDate(4, 8) },
    { type: 'gov_announcement', severity: 'info', title: 'FAME III Policy Expected Q3 2026', description: 'Government of India expected to announce FAME III scheme with increased subsidies for charging infrastructure in rural and highway corridors.', location: 'National', timestamp: istDate(3, 12) },
    { type: 'new_charger', severity: 'info', title: 'New Station: Ghaziabad Vaishali EV', description: 'ChargeZone adds 4 chargers at Vaishali Metro Station with 120kW ultra-fast.', location: 'Ghaziabad, UP', timestamp: istDate(33, 5) },
    { type: 'new_charger', severity: 'info', title: 'New Station: Faridabad Sector 15 EV', description: 'Statiq launches in Faridabad with 3 chargers.', location: 'Faridabad, Haryana', timestamp: istDate(43, 3) },
  ];

  for (const a of alerts) {
    await db.chargingAlert.create({ data: a });
  }
  console.log(`Seeded ${alerts.length} alerts`);
}

async function seedRoutes() {
  console.log('Seeding route analysis...');
  const routes = [
    { routeName: 'Delhi → Jaipur', origin: 'New Delhi', destination: 'Jaipur', totalDistanceKm: 280, chargerCount: 4, maxDistanceBetween: 95, fastChargingAvailable: true, charging24x7: true, avgWaitingTimeMin: 15, safeTravelScore: 78, recommendedStops: 'Manesar Expressway (80km), Shahpura Alwar (175km), Jaipur Tonk Road (280km)', backupStations: 'Gurgaon Cyber Hub, Bopal Ahmedabad', riskFactors: 'Long stretch between Shahpura and Jaipur (105km). Ensure 60%+ battery.' },
    { routeName: 'Bangalore → Hyderabad', origin: 'Bangalore', destination: 'Hyderabad', totalDistanceKm: 570, chargerCount: 3, maxDistanceBetween: 210, fastChargingAvailable: true, charging24x7: false, avgWaitingTimeMin: 20, safeTravelScore: 62, recommendedStops: 'Kurnool Bypass (280km), Gachibowli Hyderabad (570km)', backupStations: 'Anantapur (if added)', riskFactors: 'Large 210km gap between Bangalore and Kurnool. 24x7 availability limited. Carry portable charger.' },
    { routeName: 'Mumbai → Pune', origin: 'Mumbai', destination: 'Pune', totalDistanceKm: 150, chargerCount: 4, maxDistanceBetween: 65, fastChargingAvailable: true, charging24x7: true, avgWaitingTimeMin: 10, safeTravelScore: 92, recommendedStops: 'Lonavala Expressway (75km), Hinjewadi Pune (130km)', backupStations: 'Thane Viviana, Navi Mumbai Seawoods', riskFactors: 'Well-covered route. Weekend traffic may increase wait times at Lonavala.' },
    { routeName: 'Kolkata → Bhubaneswar', origin: 'Kolkata', destination: 'Bhubaneswar', totalDistanceKm: 450, chargerCount: 2, maxDistanceBetween: 350, fastChargingAvailable: false, charging24x7: false, avgWaitingTimeMin: 30, safeTravelScore: 35, recommendedStops: 'Kolkata Salt Lake (start), Bhubaneswar Saheed Nagar (end)', backupStations: 'None available on route', riskFactors: 'CRITICAL: 350km gap with no confirmed chargers. Not recommended for EVs below 400km range. Check for temporary setups.' },
    { routeName: 'Chennai → Kochi', origin: 'Chennai', destination: 'Kochi', totalDistanceKm: 690, chargerCount: 2, maxDistanceBetween: 550, fastChargingAvailable: false, charging24x7: false, avgWaitingTimeMin: 25, safeTravelScore: 28, recommendedStops: 'Chennai OMR (start), Kochi MG Road (end)', backupStations: 'Vellore (NH48) - slight detour', riskFactors: 'CRITICAL: 550km stretch without confirmed public charging. Not recommended for EV travel without portable charger.' },
    { routeName: 'Delhi → Agra', origin: 'New Delhi', destination: 'Agra', totalDistanceKm: 200, chargerCount: 3, maxDistanceBetween: 120, fastChargingAvailable: true, charging24x7: true, avgWaitingTimeMin: 12, safeTravelScore: 85, recommendedStops: 'Mathura Bypass (140km), Agra City (200km)', backupStations: 'Manesar Expressway, Gurgaon Cyber Hub', riskFactors: 'Well-covered Yamuna Expressway. Ensure start with 80%+ battery for comfort.' },
    { routeName: 'Delhi → Chandigarh', origin: 'New Delhi', destination: 'Chandigarh', totalDistanceKm: 250, chargerCount: 3, maxDistanceBetween: 130, fastChargingAvailable: true, charging24x7: true, avgWaitingTimeMin: 15, safeTravelScore: 80, recommendedStops: 'Karnal Highway (130km), Chandigarh Sector 17 (250km)', backupStations: 'Manesar Expressway', riskFactors: 'Moderate coverage. NH44 corridor improving. Start with 80% battery.' },
    { routeName: 'Mumbai → Ahmedabad', origin: 'Mumbai', destination: 'Ahmedabad', totalDistanceKm: 530, chargerCount: 3, maxDistanceBetween: 250, fastChargingAvailable: true, charging24x7: false, avgWaitingTimeMin: 20, safeTravelScore: 52, recommendedStops: 'Surat Dumas Road (260km), Ahmedabad SG Highway (530km)', backupStations: 'Thane Viviana, Navi Mumbai Seawoods', riskFactors: '250km Mumbai-Surat gap is challenging. NH48 Vadodara stretch improving.' },
  ];

  for (const r of routes) {
    await db.routeAnalysis.create({ data: r });
  }
  console.log(`Seeded ${routes.length} route analyses`);
}

async function seedInvestments() {
  console.log('Seeding investment opportunities...');
  const investments = [
    { location: 'Manesar Industrial Area', state: 'Haryana', city: 'Manesar', trafficDensity: 'high', tourismPotential: false, evPopulation: 4500, existingChargerDist: 2.5, nearbyRestaurants: 12, nearbyFuelStations: 5, nearbyMalls: 2, nearbyHotels: 8, nearbyParking: 15, expectedUtilization: 0.72, roiPotential: 'high', priorityScore: 88 },
    { location: 'Vijayawada Highway Junction', state: 'Andhra Pradesh', city: 'Vijayawada', trafficDensity: 'very_high', tourismPotential: true, evPopulation: 2800, existingChargerDist: 18, nearbyRestaurants: 8, nearbyFuelStations: 6, nearbyMalls: 1, nearbyHotels: 5, nearbyParking: 10, expectedUtilization: 0.65, roiPotential: 'very_high', priorityScore: 92 },
    { location: 'Shimla Mall Road', state: 'Himachal Pradesh', city: 'Shimla', trafficDensity: 'high', tourismPotential: true, evPopulation: 800, existingChargerDist: 45, nearbyRestaurants: 15, nearbyFuelStations: 2, nearbyMalls: 0, nearbyHotels: 20, nearbyParking: 5, expectedUtilization: 0.55, roiPotential: 'high', priorityScore: 85 },
    { location: 'CST Mumbai Area', state: 'Maharashtra', city: 'Mumbai', trafficDensity: 'very_high', tourismPotential: true, evPopulation: 12000, existingChargerDist: 1.2, nearbyRestaurants: 25, nearbyFuelStations: 3, nearbyMalls: 4, nearbyHotels: 18, nearbyParking: 20, expectedUtilization: 0.82, roiPotential: 'very_high', priorityScore: 95 },
    { location: 'Mysore Palace Road', state: 'Karnataka', city: 'Mysore', trafficDensity: 'high', tourismPotential: true, evPopulation: 2200, existingChargerDist: 8, nearbyRestaurants: 18, nearbyFuelStations: 4, nearbyMalls: 2, nearbyHotels: 15, nearbyParking: 8, expectedUtilization: 0.68, roiPotential: 'high', priorityScore: 87 },
    { location: 'Coorg Madikeri Town', state: 'Karnataka', city: 'Madikeri', trafficDensity: 'medium', tourismPotential: true, evPopulation: 400, existingChargerDist: 85, nearbyRestaurants: 10, nearbyFuelStations: 2, nearbyMalls: 0, nearbyHotels: 12, nearbyParking: 3, expectedUtilization: 0.48, roiPotential: 'medium', priorityScore: 72 },
    { location: 'Varanasi Godaulia Chowk', state: 'Uttar Pradesh', city: 'Varanasi', trafficDensity: 'very_high', tourismPotential: true, evPopulation: 1500, existingChargerDist: 12, nearbyRestaurants: 20, nearbyFuelStations: 5, nearbyMalls: 1, nearbyHotels: 25, nearbyParking: 6, expectedUtilization: 0.62, roiPotential: 'high', priorityScore: 84 },
    { location: 'Goa Panjim Market', state: 'Goa', city: 'Panaji', trafficDensity: 'high', tourismPotential: true, evPopulation: 600, existingChargerDist: 22, nearbyRestaurants: 30, nearbyFuelStations: 3, nearbyMalls: 1, nearbyHotels: 35, nearbyParking: 8, expectedUtilization: 0.58, roiPotential: 'high', priorityScore: 86 },
    { location: 'Rishikesh Laxman Jhula', state: 'Uttarakhand', city: 'Rishikesh', trafficDensity: 'high', tourismPotential: true, evPopulation: 500, existingChargerDist: 35, nearbyRestaurants: 12, nearbyFuelStations: 2, nearbyMalls: 0, nearbyHotels: 20, nearbyParking: 4, expectedUtilization: 0.52, roiPotential: 'medium', priorityScore: 76 },
    { location: 'Jaipur Amer Fort Area', state: 'Rajasthan', city: 'Jaipur', trafficDensity: 'very_high', tourismPotential: true, evPopulation: 3000, existingChargerDist: 10, nearbyRestaurants: 15, nearbyFuelStations: 3, nearbyMalls: 2, nearbyHotels: 18, nearbyParking: 8, expectedUtilization: 0.7, roiPotential: 'high', priorityScore: 89 },
  ];

  for (const inv of investments) {
    await db.investmentOpportunity.create({ data: inv });
  }
  console.log(`Seeded ${investments.length} investment opportunities`);
}

async function seedDeserts() {
  console.log('Seeding charging deserts...');
  const deserts = [
    { location: 'Leh-Manali Highway', state: 'Jammu & Kashmir/Ladakh/Himachal Pradesh', nearestCharger: 'Leh City (limited)', nearestChargerDistanceKm: 200, roadCondition: 'poor', mobileNetwork: 'no_signal', recommendedBatteryPct: 100, recommendedMinRangeKm: 500, emergencyChargingAlt: 'Hotel generators (slow, expensive)', nearbyHotels: 3, nearbyRepairShops: 0, nearbyHospitals: 1, policeStationDistanceKm: 120, towingAvailable: false, riskLevel: 'critical' },
    { location: 'Spiti Valley Circuit', state: 'Himachal Pradesh', nearestCharger: 'Manali / Shimla', nearestChargerDistanceKm: 150, roadCondition: 'poor', mobileNetwork: '2G', recommendedBatteryPct: 100, recommendedMinRangeKm: 400, emergencyChargingAlt: 'Guest house generators', nearbyHotels: 5, nearbyRepairShops: 0, nearbyHospitals: 1, policeStationDistanceKm: 80, towingAvailable: false, riskLevel: 'critical' },
    { location: 'Rann of Kutch', state: 'Gujarat', nearestCharger: 'Bhuj City', nearestChargerDistanceKm: 85, roadCondition: 'fair', mobileNetwork: '3G', recommendedBatteryPct: 90, recommendedMinRangeKm: 250, emergencyChargingAlt: 'Resort generators', nearbyHotels: 4, nearbyRepairShops: 1, nearbyHospitals: 1, policeStationDistanceKm: 60, towingAvailable: false, riskLevel: 'high' },
    { location: 'NH44 Salem-Coimbatore Gap', state: 'Tamil Nadu', nearestCharger: 'Salem / Coimbatore', nearestChargerDistanceKm: 120, roadCondition: 'good', mobileNetwork: '4G', recommendedBatteryPct: 75, recommendedMinRangeKm: 200, emergencyChargingAlt: 'Fuel station power outlets', nearbyHotels: 8, nearbyRepairShops: 3, nearbyHospitals: 4, policeStationDistanceKm: 25, towingAvailable: true, riskLevel: 'medium' },
    { location: 'Konkan Coast (Murudeshwara to Goa)', state: 'Karnataka/Goa', nearestCharger: 'Goa Panjim / Mangalore', nearestChargerDistanceKm: 140, roadCondition: 'fair', mobileNetwork: '4G', recommendedBatteryPct: 85, recommendedMinRangeKm: 250, emergencyChargingAlt: 'Beach resort generators', nearbyHotels: 10, nearbyRepairShops: 2, nearbyHospitals: 3, policeStationDistanceKm: 35, towingAvailable: true, riskLevel: 'high' },
    { location: 'Rajasthan Desert Route (Jaisalmer-Jodhpur)', state: 'Rajasthan', nearestCharger: 'Jodhpur City', nearestChargerDistanceKm: 200, roadCondition: 'good', mobileNetwork: '3G', recommendedBatteryPct: 95, recommendedMinRangeKm: 350, emergencyChargingAlt: 'Highway dhaba generators', nearbyHotels: 3, nearbyRepairShops: 1, nearbyHospitals: 1, policeStationDistanceKm: 80, towingAvailable: false, riskLevel: 'critical' },
    { location: 'Northeast Corridor (Guwahati-Shillong)', state: 'Assam/Meghalaya', nearestCharger: 'Guwahati GS Road', nearestChargerDistanceKm: 100, roadCondition: 'fair', mobileNetwork: '4G', recommendedBatteryPct: 80, recommendedMinRangeKm: 200, emergencyChargingAlt: 'Hotel backup power', nearbyHotels: 5, nearbyRepairShops: 1, nearbyHospitals: 2, policeStationDistanceKm: 40, towingAvailable: true, riskLevel: 'medium' },
    { location: 'Central India (Bhopal-Nagpur NH44)', state: 'Madhya Pradesh/Maharashtra', nearestCharger: 'Nagpur City', nearestChargerDistanceKm: 160, roadCondition: 'good', mobileNetwork: '4G', recommendedBatteryPct: 85, recommendedMinRangeKm: 280, emergencyChargingAlt: 'Fuel station power', nearbyHotels: 6, nearbyRepairShops: 2, nearbyHospitals: 3, policeStationDistanceKm: 30, towingAvailable: true, riskLevel: 'high' },
  ];

  for (const d of deserts) {
    await db.chargingDesert.create({ data: d });
  }
  console.log(`Seeded ${deserts.length} charging deserts`);
}

async function main() {
  try {
    await seedStations();
    await seedAlerts();
    await seedRoutes();
    await seedInvestments();
    await seedDeserts();
    console.log('\n✅ All seed data inserted successfully!');
  } catch (error) {
    console.error('Seed error:', error);
    process.exit(1);
  } finally {
    await db.$disconnect();
  }
}

main();